WIP Feature/issue 4
rusinikita/devex pull request #8
Opened 2023-08-13 16:02 UTC by demoneno4ec

- [+] Добавить структуру для миграции в бд

2023-08-16 19:54 UTC, rusinikita requested changes
Давай следовать конвенции коммитов и писать их на английском. Сделай squash в 1-3 коммита с изменением сообщения.

https://cbea.ms/git-commit/

issue упоминай как #4 в подвале коммит сообщения

2023-08-16 19:54 UTC, rusinikita commented on datacollector/main.go
> +		err        error
Давай использовать `:=` для объявления переменных на месте их создания. Я считаю оправданным объявлять переменные заранее, только для использования в цикле или многопоточности

2023-08-16 19:54 UTC, rusinikita commented on datacollector/main.go
> +	closeFile(file)
2 раза закрываешь файл. defer file.Close() достаточно. Не беда, что ошибка не проверяется, это cli

2023-08-16 19:54 UTC, rusinikita commented on datacollector/main.go
> +		lintErrors []project.LintError
То же самое, что выше. Не выделяем память, далеко от использования

2023-08-16 19:54 UTC, rusinikita commented on datacollector/main.go
> +	tx := database.Begin()
Используй database.Transaction(func...). Но я не вижу смысла в усложнении пока. Это однопользовательская программа

2023-08-16 19:54 UTC, rusinikita commented on datacollector/main.go
> +		fileId project.ID
fileID и err принадлежат области видимости цикла. Давай перенесем их туда.

2023-08-16 19:54 UTC, rusinikita commented on datacollector/main.go
> +		result []project.LintError
Если хочешь объявить пустой список, но не хочешь заморачиваться с make(...), то объяви в возвращаемых параметрах функции (result []project.LintError, err error)

2023-08-16 19:54 UTC, rusinikita commented on datacollector/main.go
> +	return 0, errors.New("по неизвестной причине, id файла не обнаружено в бд")
Язык проекта - английский

2023-08-16 19:54 UTC, rusinikita commented on datacollector/main.go
> +		fmt.Printf("Файл не был закрыт, ошибка: %s \n\r", err)
Язык проекта - английский

2023-08-16 19:54 UTC, rusinikita commented on project/project.go
> +// LintFile TODO Сделал т.к. не устраивает текущая структура files
Исплользуй, пожалуйста, существующую структуру. Иначе сложно будет визуализировать. Перечисли, что улучшить, в issue. И возьмем исправление позже

2023-08-16 19:54 UTC, rusinikita commented on project/project.go
> +	FileId     ID        `gorm:"column:field_id;not null;index;comment:'Внешний ключ на файл'"`
Язык проекта - английский

2023-08-16 19:54 UTC, rusinikita commented on datasource/main.go
> +		project.LintError{},
Не добавил LintFile, произойдет ошибка. Но ниже я просил удалить LintFile

2023-08-17 19:30 UTC, demoneno4ec commented on datacollector/main.go
> +		err        error
+

2023-08-17 19:35 UTC, demoneno4ec commented on datacollector/main.go
> +	closeFile(file)
Да, делал это осознанно, ок

2023-08-17 19:37 UTC, demoneno4ec commented on datacollector/main.go
> +	tx := database.Begin()
Это не про concurrency, а про то чтобы изменения были согласованные. 

лока бд вроде не делаю.

Но если настаиваешь, сделаю

2023-08-17 19:43 UTC, demoneno4ec commented on datacollector/main.go
> +		fileId project.ID
+

2023-08-17 19:44 UTC, demoneno4ec commented on datacollector/main.go
> +	return 0, errors.New("по неизвестной причине, id файла не обнаружено в бд")
+

2023-08-17 19:45 UTC, demoneno4ec commented on datacollector/main.go
> +		fmt.Printf("Файл не был закрыт, ошибка: %s \n\r", err)
метод удалил, сообщение ушло

2023-08-17 19:52 UTC, demoneno4ec commented on project/project.go
> +// LintFile TODO Сделал т.к. не устраивает текущая структура files
Тут критичное
1. File.Package + File.Name - не путь файла, а частное для go modules не для всех языков, так образуется рбаота с пакетами, namespaces
2. критичное, т.к. сильно усложняет поиск по пути, id файла для последующей вставки связанных записей

не критичное
1. Lines
    - кажется, что это часть какой-то частной бизнес логики, а не отношение к файлам
    - но можно и оставить (возможно надумал)
    - накладывает доп расходы на парсинг, пусть и спички;
2. Symbols 
    -  кажется, что это часть какой-то частной бизнес логики, а не отношение к файлам;
    - не понимаю, как использовать;
    - накладывает доп расходы на парсинг, пусть и спички;
3. Tags
    - не понял, за что отвечает; 
    - не понимаю как использовать в разрезе lint_errors;
    - сделал вывод, что здесь какая то подмешенная логика, а не про файлы;
    - накладывает доп расходы на парсинг, пусть и спички;
4. Imports
    - не понял, за что отвечает;
    - не понимаю как использовать в разрезе lint_errors;
    - сделал вывод, что здесь какая то подмешенная логика, а не про файлы;
    - накладывает доп расходы на парсинг, пусть и спички;
5. Present
    - не понял, за что отвечает; 
    - не понимаю как использовать в разрезе lint_errors;
    - сделал вывод, что здесь какая то подмешенная логика, а не про файлы;
    - накладывает доп расходы на парсинг, пусть и спички;

2023-08-20 10:40 UTC, rusinikita commented on datacollector/main.go
> +		err        error
Использовать то же нахвание для переменной ошибки. Она будет переобъявлена

2023-08-20 10:43 UTC, rusinikita commented on project/project.go
> +// LintFile TODO Сделал т.к. не устраивает текущая структура files
Непонятные поля используются в отрисовки графиков. В твоём алгоритме не нужно создавать новые сущности файлов, а нужно присоединить данные об ошибках к имеющимся в БД файлам

2023-08-20 10:45 UTC, rusinikita commented on project/project.go
> +// LintFile TODO Сделал т.к. не устраивает текущая структура files
На поиск по пути можешь посмотреть в алгоритме парсинга git. Там осуществляется поиск существующих файлов, чтобы прикрепить данные о коммитах к ним.

2023-08-20 15:02 UTC, demoneno4ec commented on datacollector/main.go
> +		err        error
тут понятно

2023-08-20 15:17 UTC, demoneno4ec commented
- [ ] сделать сквош комитов 3 штуки
- [ ] комиты на английском
- [ ] комменты к структурам на английском
- [ ] используем project.file вместо project.LintFile (с todo issue #9)

2023-08-21 19:11 UTC, rusinikita approved these changes

2023-08-21 19:13 UTC, rusinikita commented
@demoneno4ec Сделай rebase и вольем. Сейчас какой-то конфликт не позволяет влить

2023-08-22 09:59 UTC, merged